version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app_db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8181:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'app_db'
      ME_CONFIG_MONGODB_AUTH_USERNAME: 'app_user'
      ME_CONFIG_MONGODB_AUTH_PASSWORD: 'app_pass'
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    depends_on:
      - mongo

  webapp:
    image: vslugin/nodeapp:latest
    restart: always
    environment:
      JWT_SECRET: 'SuperSuperSecret'
      BCRYPT_SALT_ROUNDS: 20
      JWT_TTL_PERIOD: 300
      MONGODB_CONNECTION_STRING: 'mongodb://root:example@mongo:27017/admin'
    ports:
      - "80:3000"
    command: "node /opt/webapp/bin/www"
